### PR TITLE
`cppm --toml` fix

### PR DESCRIPTION
**Pull request by BrandonDoesDev**
It just runs the command as a superuser now, since the original error message states that the "permission was denied"

### CODE REVIEW

**Review by Maou-Shimazu — COMMENTED** [review]
You cant spawn sudo on windows by default so this solution wont work on windows.

**Comment by Maou-Shimazu** [comment]
Ill look into a better solution and add it to this pr.

**Comment by BrandonDoesDev** [comment]
I'll look into it as well

**Comment by BrandonDoesDev** [comment]
Current solution doesn't work, so I'm closing this

**Pull request closed without merging**
